# Introduction {#intro}

Vomiting and regurgitation are commonly encountered in out-hospital-cardiac arrest with a reported incidence of 20–30% [@voss_how_2014; @simons_incidence_2007]. This is of concern since patients who have suffered an OHCA, are already in extremis. If standard suctioning techniques are not sufficient to maintain a clear airway and provide ventilation, then these patients will die, irrespective of the quality of chest compressions and the timeliness of defibrillation. Arguably, tracheal intubation is the preferred airway management technique in patients with ongoing airway contamination, but there is evidence that this is difficult to achieve when the airway is soiled [@sakles_impact_2017]. Even if patients survive to the hospital, it is possible that aspiration pneumonias may adversely affect survival outcome, although this has yet to be proved empirically [@christ_early-onset_2016].

Traditional suctioning techniques have been criticised, and training in the management of contaminated airways, limited. This has led to the development of a combined suction/laryngoscopy technique to facilitate intubation, known as Suction Assisted Laryngoscopy and Airway Decontamination (SALAD), and the creation of modified airway manikins to allow for practice in these techniques  [@ducanto_novel_2017].

However, to date there has only been one study specifically looking at the SALAD technique and the outcomes were self-reported confidence measures of trainees in using the technique. Other techniques have been described to manage significant airway contamination, including the use of a meconium aspirator [@kei_comparing_2017], which is not practical in the out-of-hospital environment (and requires a device that is not typically carried by UK ambulance services), and deliberate intubation of the oesophagus (the oesophageal diversion manoeuvre), of which the sum total of evidence in support of the procedure is a single case report [@kornhall_intentional_2015].

Prior to undertaking clinical studies, it is important to determine the feasibility of teaching the technique to paramedics in a brief training session, and testing whether it has a beneficial effect on paramedic intubation success. Training necessarily needs to be concise given the operational demands of the ambulance service at present, which is placing training time under increasing pressure. A training programme that required a whole day to undertake, for example, would not be pragmatic to implement.

In this study, the primary outcome measure of interest is first-pass intubation success. There are published values on non-physician first-pass intubation success, which is reported to be approximately 70%, although this is likely to be lower in soiled airways.8 Arguably, overall intubation success could also be an indication of intubation competence, but by not allowing multiple intubation attempts at each stage of the assessment, the participants are minimally inconvenienced in terms of time required to take part in the study, while still providing an objective measurements of the effect of the training intervention.
