--- 
title: "SATIATED"
author: "Richard Pilbery"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: article
output: bookdown::word_document2
bibliography: [references.bib, packages.bib]
biblio-style: apalike
toc: no
link-citations: yes
github-repo: RichardPilbery/generic-bookdown
always_allow_html: yes
geometry: margin=2cm
header-includes:
  \AtBeginDocument{\let\maketitle\relax}
---

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')

  library(readr)
  background <- read_file("01-introduction.Rmd")
  methods <- read_file("02-method.Rmd")
  results <- read_file("03-results.Rmd")
  discussion <- read_file("04-discussion.Rmd")
  summary <- read_file("05-conclusion.Rmd")
  
  allwords <- paste(background, methods, results, discussion, summary)
  
  prep_text <- function(text){
  
    # remove all line breaks, http://stackoverflow.com/a/21781150/1036500
    text <- gsub("[\r\n]", " ", text)
  
    # don't include front yaml
    text <- gsub("---.*--- ", "", text)
  
    # don't include text in code chunks: https://regex101.com/#python
    text <- gsub("```\\{.+?\\}.+?```", "", text)
  
    # don't include text in in-line R code
    text <- gsub("`r.+?`", "", text)
  
    # don't include HTML comments
    text <- gsub("<!--.+?-->", "", text)
  
    # don't include LaTeX comments
    # how to do this? %%
  
    # don't include inline markdown URLs
    text <- gsub("\\(http.+?\\)", "", text)
  
    # don't include images with captions
    text <- gsub("!\\[.+?\\)", "", text)
  
    # don't include # for headings
    text <- gsub("#*", "", text)
  
    # don't include html tags
    text <- gsub("<.+?>|</.+?>", "", text)
  
      # don't include percent signs because they trip up stringi
    text <- gsub("%", "", text)
  
    # don't include LaTeX \eggs{ham}
    # how to do? problem with capturing \x
  
  
    if(nchar(text) == 0){
      stop("You have not selected any text. Please select some text with the mouse and try again")
    } else {
  
    return(text)
  
    }
  
  }
  
  # https://stackoverflow.com/questions/8920145/count-the-number-of-words-in-a-string-in-r
  library(stringr)
  nwords <- function(string, pseudo=F){
    ifelse( pseudo, 
            pattern <- "\\S+", 
            pattern <- "[[:alpha:]]+" 
          )
    str_count(string, pattern)
  }
  
  numberOfWords <- nwords(prep_text(allwords))
  
```
`r if (!knitr:::is_html_output()) '
# Soiled Airway Tracheal Intubation and the Effectiveness of Decontamination by Paramedics (SATIATED): A randomised controlled manikin study-
'`
`r if (knitr:::is_html_output()) '
# Preamble
'`

## Author information
| **Richard Pilbery**
| Research paramedic
| Yorkshire Ambulance Service NHS Trust
| Springhill, Brindley Way
| Wakefield 41 Business Park
| Wakefield
| WF2 0XQ

ORCID: [https://orcid.org/0000-0002-5797-9788](https://orcid.org/0000-0002-5797-9788)

| email: r.pilbery@nhs.net
| tel: 

| **Dr. M. Dawn Teare**
| Reader in Epidemiology and Biostatistics
| University of Sheffield

**Word count:** `r numberOfWords`

**Keywords:** Intubation, Emergency Medical Services, Airway obstruction 

## Abstract

### Introduction
Vomiting and regurgitation are commonly encountered in out-hospital-cardiac arrest (OHCA) with a reported incidence of 20–30%. This is of concern since patients who have suffered an OHCA are already in extremis. If standard suctioning techniques are not sufficient to maintain a clear airway and provide ventilation, then these patients will die, irrespective of the quality of chest compressions and the timeliness of defibrillation. This study aimed to determine whether a short teaching session of the Suction Assisted Laryngoscopy and Airway Decontamination (SALAD) technique, improved paramedics' ability to successfully intubate a contaminated airway.

### Methods
A modified airway manikin with the oesophagus connected to a reservoir of ‘vomit’, and a bilge pump capable of propelling the vomit up into the oropharynx, was used to simulate a soiled airway. The intervention consisted of a brief SALAD training session with a demonstration and opportunity to practice. Participants were randomly allocated into two groups: AAB who made two pre-training intubation attempts and one post-training attempt, and ABB, who made one pre-training and two post-training attempts, to adjust for improvement in performance due to repetition.


### Results
In this manikin study, following a brief SALAD training session, more paramedics were able to intubate a soiled airway on their first attempt, compared to those without training (90.2% vs 53.7%, difference of 36.6%, 95%CI 24–49.1%, p<0.001). In addition, the mean difference in time taken to perform a successful intubation between groups was statistically significant for attempts 1 and 2 (mean difference 11.71 seconds, 95% CI 1.95– 21.47 seconds, p=0.02), but not attempts 1 and 3 (mean difference -2.52 seconds, 95% CI -11.64–6.61 seconds, p=0.58)). This result is likely to be confounded by the use of tracheal suction, which only occurred in the post-training attempts, and added additional time to the intubation attempts. There was no statistically significant difference in success rates on the third attempt between AAB and ABB (89.0% vs 86.6%, difference 2.4%, 95%CI 7.6–12.4%, p=0.63).

### Conclusion
In this study, the use of the SALAD technique significantly improved first attempt success rates when paramedics were intubating a simulated soiled airway.


